### ISSUE TITLE
Why do we need install typescript globally? 

### ISSUE THREAD

**Issue by nghiahung-dev** [yrming/vscode-type-challenges#27]
# Description
I want to install typescript locally for type-challenges extensions because I saw install typescript globally is not good. 

# Trade-offs:
Global installation is more convenient for individual use and rapid development, but it can create problems when managing multiple projects with differing TypeScript requirements.
Local installation requires more setup per project but provides much better control, especially in a team environment or when working on multiple projects with varying needs.
In general, for long-term or team projects, installing TypeScript locally is usually the better practice for maintainability and avoiding version conflicts. For quick experimentation or solo development, installing it globally can be convenient.

# Question
Should we support typescript inside the extension?

**Comment by yrming** [comment]
Thanks for your issue. When I developed this extension, my idea was relatively simple. I just wanted to have a globally available tsc command. But from my point of view, global installation and local installation don't seem to conflict much, because local projects will intentionally install a certain version of ts and set it up.

However, I should really consider removing the restriction that ts must be installed globally before using this extension.
